language: node_js
node_js:
  - "8"
stages:
  - Build
  - Server
  - Client 
env:
  - PORT=3000
  - DBURL=mongodb://localhost/guaurderia

jobs:
  include:
    - stage: Build
      script: npm install
    - stage: Server
      script: npm install && npm start
    - stage: Client
      script: npm install && npm start